<a href="https://colab.research.google.com/github/KINGSANGWOON/school/blob/main/3_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
grape = np.array([[19,300,0],[20,500,0],[18,400,0],[25,500,1],[27,700,1],[28,600,1]])

In [ ]:
X = grape[:,:2]
y = grape[:,2]
print(X)
print(y)

[[ 19 300]
 [ 20 500]
 [ 18 400]
 [ 25 500]
 [ 27 700]
 [ 28 600]]
[0 0 0 1 1 1]


In [ ]:
# 로지스틱 회귀 알고리즘으로 학습
from sklearn.linear_model import LogisticRegression
model = LogisticRegression() #LB모델 생성
model.fit(X,y) #학습
print(model.coef_)  # 가중치 출력 
model.coef_
print(model.intercept_)

[[0.71665314 0.04838074]]
[-40.31573036]


In [ ]:
print(model.predict([[22,600]]))
print(model.predict([[20,500]]))

[1]
[0]


In [ ]:
print(model.score(X,y))

1.0


In [ ]:
size= float(input('포도 한 알의 크기는(mm):'))
weight = float(input('포도 한 송이의 무게는(g):'))
result = model.predict([[size,weight]])
if result == 1:
  print('거봉')
else:
  print('일반 포도알')

포도 한 알의 크기는(mm):123
포도 한 송이의 무게는(g):123
거봉
